import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Head from 'next/head';
import ServiceWorkerRegistration from './ServiceWorkerRegistration';
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  console.log('root layout');
  return (
    <html lang="en">
      <Head>
        {/* <link rel="manifest" href="/manifest.json" /> */}
        <link rel="icon" href="/icon-192x192.png" />
        <meta name="theme-color" content="#qwr456" />
        <title>root title</title>
      </Head>
      <body>
        {children}
        <ServiceWorkerRegistration />
      </body>
    </html>
  );
}
